services:
  db:
    image: postgres:14-alpine
    container_name: vkedu-postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vkedu-app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: >
      sh -c "java -jar /app.jar
      --spring.profiles.active=${SPRING_PROFILES_ACTIVE}
      --server.port=${SERVER_PORT}"

volumes:
  db-data:
